server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-1-service
          uri: lb://ms-1-service
          predicates:
            - Path=/files/**
        - id: ms-2-service
          uri: lb://ms-2-service
          predicates:
            - Path=/ms2/**
        - id: ms-3-service
          uri: lb://ms-3-service
          predicates:
            - Path=/ms3/**
        - id: ms-4-service
          uri: lb://ms-4-service
          predicates:
            - Path=/ms4/**
        - id: ms-5-service
          uri: lb://ms-5-service
          predicates:
            - Path=/ms5/**
